### ISSUE TITLE
Different hotkeys in different contexts

### ISSUE THREAD

**Issue by andertun** [nerdmed/hotkeys#6]
Is it possible to have a hotkey for "ctrl + s" in a certain context but not globally?

After I call `contextHotkeys.unload();` and press "ctrl + s" I get this error: `Uncaught TypeError: undefined is not a function` in mousetrap_mousetrap.js:485, because the globalHotkeys don't have this combo.

**Comment by andertun** [comment]
Ok, sounds good that it should work like how I described it. But right now I have to create a global hotkey for the local shortcut "ctrl + s" (with a  a noop function as callback), otherwise I get the error.

**Comment by nerdmed** [comment]
Hey @andertun  i could not reproduce it on the fly but i am very sure to see the issue inside the code. I have published flowkey:hotkeys@1.1.1 - would be great to hear if that version fixes this issue?

**Comment by andertun** [comment]
Yes flowkey:hotkeys@1.1.1 fixes this issue. Thank you!
