### ISSUE TITLE
Arrow key detection and ASCII code

### ISSUE THREAD

**Issue by babnik63** [nerdmed/hotkeys#7]
Is there any method to detect arrow keys(right-left)? and how can we use ASCII code of keys?

**Comment by babnik63** [comment]
Solved:
up up down down left right left right b a enter   are the codes,
BUT how about ASCII?

**Comment by nerdmed** [comment]
hey @babnik63  i am using internally [mousetrap](http://craig.is/killing/mice) - you can have a look to see all supported features. What do you want to use as ascii characters - maybe i can help

**Comment by babnik63** [comment]
Thank you, I think mousetrap has good support for most of keys.
